### ISSUE TITLE
Url trait error while building

### ISSUE THREAD

**Issue by LHolten** [FlorianUekermann/rustls-acme#10]
I get this error when trying to build a project with rustls-acme
```
error[E0277]: the trait bound `Url: From<&str>` is not satisfied
  --> C:\Users\Lucas\.cargo\registry\src\github.com-1ecc6299db9ec823\rustls-acme-0.1.6\src\https_helper.rs:16:23
   |
16 |     let mut request = Request::new(method, url.as_ref());
   |                       ^^^^^^^^^^^^ the trait `From<&str>` is not implemented for `Url`
   |
   = note: required because of the requirements on the impl of `std::convert::Into<Url>` for `&str`
   = note: required because of the requirements on the impl of `TryFrom<&str>` for `Url`
```
Maybe one of the dependencies is broken?

**Comment by FlorianUekermann** [comment]
I can't reproduce this. Is the code you are compiling public, or could you provide a reproducer?

Or alternatively could you run `cargo build` for this repo and see if the error still appears?

Any other hints, do you use any particular features on your dependencies?

**Comment by LHolten** [comment]
Compiling this repo and the examples works fine, i will investigate the difference with the usage in my project.

**Comment by FlorianUekermann** [comment]
Could you share your Cargo.toml?

**Comment by LHolten** [comment]
I have figured out the difference:
My project pulls in `http-types 1.12.0` -> `url 2.1.1` which does not implement `TryFrom<&str> for Url`
This repo pulls in `http-types 1.12.0` -> `url 2.2.2` which does implement `TryFrom<&str> for Url`
I have no idea why this repo gets a newer version of `url`, because `http-types 1.12.0` has old `url 2.1.1` as dependency

**Comment by LHolten** [comment]
my Cargo.toml
```
[package]
name = "gridentify"
version = "0.1.0"
authors = ["Hytak <lhc.holten@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
array-init = "0.1.1"
rand = "0.7.3"
serde_json = "1.0.44"
tungstenite = "0.9.2"
ratelimit_meter = "5.0.0"
simple-error = "0.2.1"
async-std = "1.8"
rustls-acme = { git = "https://github.com/FlorianUekermann/rustls-acme" }

[dependencies.serde]
version = "1.0.104"
features = ["derive"]

[dependencies.rusqlite]
version = "0.21.0"
features = ["bundled"]
```

**Comment by LHolten** [comment]
It must be because of the old version of tungstenite i'm using that depends on `url 2.1`

**Comment by FlorianUekermann** [comment]
Thanks. I'll update the dependencies to make this implicit dependency more explicit.

**Comment by LHolten** [comment]
Removing the old tungstenite and running `cargo update` solved the error.
If you could indeed make the implicit dependency explicit i think this issue is solved.

**Comment by FlorianUekermann** [comment]
I added an explicit dependency on `url = "2.2"` and tagged v0.1.7 of this crate. Thanks for the report.

I wonder if there is an automatic way to find minimal version requirements with cargo. It would require some build time, but a tool bisecting minor and patch subdependency versions would by super handy to catch these issues in libraries.

**Comment by FlorianUekermann** [comment]
I think this should do the trick.
```
rm Cargo.lock
cargo build -Z minimal-versions
```
I already found more issues, but I think they are caused by inaccurate subdependencies, so I'll report them there when I have some time.
