### ISSUE TITLE
Add an optional `tonic` feature with tonic compatibility helpers?

### ISSUE THREAD

**Issue by hdevalence** [FlorianUekermann/rustls-acme#38]
We're using `rustls-acme` with `tonic`, and so far we wrote a some boilerplatey code to hook up `rustls-acme` to Tonic's batteries-included server implementation.

If we extracted that code and submitted a PR, would you be interested in upstreaming it under a feature flag?

I'm imagining implementing an extension trait, say `AcmeTonicExt`, so that instead of writing
```rust
Server::builder()
    .add_service(/* ... */)
    .add_service(/* ... */)
    .serve(addr)
```
for an http server, it would be possible to write
```rust
Server::builder()
    .add_service(/* ... */)
    .add_service(/* ... */)
    .serve_with_acme_tls(addr, acme_config)
```
for an auto-https server.  The `serve_with_acme_tls` method would be provided by the extension trait, and handle gluing the `rustls-acme` methods to the `tonic` `serve_with_incoming` method.

**Comment by FlorianUekermann** [comment]
I'm definitely open to this. I'm not familiar with tonic, but if you send a PR or a more detailed sketch I'll happily review.

**Comment by FlorianUekermann** [comment]
It's been a while, I'll close here, assuming there's no interest anymore. Feel free to reopen.
