### ISSUE TITLE
Support for rustls version 0.22.0

### ISSUE THREAD

**Issue by blueowlgreenfish** [FlorianUekermann/rustls-acme#55]
[https://github.com/rustls/rustls/releases/tag/v%2F0.22.0](https://github.com/rustls/rustls/releases/tag/v%2F0.22.0)

**Comment by FlorianUekermann** [comment]
Thanks. I need to wait for the futures-rustls release, but I expect that to happen shortly.

**Comment by cpu** [comment]
I started a branch for the futures-rustls update: https://github.com/rustls/futures-rustls/pull/6

**Comment by cpu** [comment]
[rustls-futures 0.25](https://crates.io/crates/futures-rustls/0.25.0) is now available with support for Rustls 0.22.

**Comment by FlorianUekermann** [comment]
I released 0.8 with futures-rustls 0.25
