### ISSUE TITLE
Support for email addresses

### ISSUE THREAD

**Issue by jsha** [FlorianUekermann/rustls-acme#6]
Hi! Let's Encrypt engineer here. I filed an issue over at https://github.com/http-rs/tide-acme/issues/2 requesting that tide-acme show how to include an email address in the example code. @joshtriplett pointed out that email addresses are actually not supported by rustls-acme. Could I ask you to add support for providing an email address? Our experience with ACME clients has been that people don't go out of their way to configure an email address if it's not in the default, but if it is in the default, they're usually happy to provide it.

Providing the email address has a lot of advantages. The main one is that the user can get expiration emails, but also when clients are buggy and spam the service, we really make an effort to connect the user with the client developer so the bugs can be fixed. That starts with an email to the user. Also, we occasionally make breaking changes to our API and need to email our users about it.

If the example email domain is, e.g. example.com, Boulder will reject it until the user provides a different email address.

**Comment by FlorianUekermann** [comment]
Thanks for filling this issue. I'll need to think about the api for a few days.

**Comment by joshtriplett** [comment]
@FlorianUekermann Long-term, I'd suggest a builder-style API that creates an opaque `RustlsAcmeConfig` object, so that you can add future configuration options in a backwards-compatible way.

**Comment by FlorianUekermann** [comment]
I added a `with_contact` constructor to `ResolvesServerCertUsingAcme` for now, which allows at least the runtime independent API to use a contact. The resolver fields are private, so this does not preclude switching to a `RustlsAcmeConfig` embedded in the resolver later.

Let's encrypt doesn't seem to update account info, so I'm hashing the contacts to derive a new file name for the cached account key file name. Cached certificates are not affected by this. I'm not sure yet if I should add the kid, account config or public key to their hash, so I skipped it for now.

I would like to publish 0.2 with a revised API soonish, which should encapsulates all config in `RustlsAcmeConfig` and replaces the simple API with a runtime independent one (the spawn fn becomes an argument). That makes it trivial to add a convenience module or `run_x` method for each runtime (or none, using threads). Until then specifying contact won't be available in the simple API.

Anyway, 0.1.6 is released and should unblock @joshtriplett for now.

**Comment by jsha** [comment]
> Let's encrypt doesn't seem to update account info

Subscribers can update their own account info (particularly contacts) via the ACME API. The Let's Encrypt servers don't _generally_ modify contacts unilaterally, but we may do this from time to time, for instance for invalid email addresses or upon a GDPR request.

> I'm hashing the contacts to derive a new file name for the cached account key file name. Cached certificates are not affected by this. I'm not sure yet if I should add the kid, account config or public key to their hash, so I skipped it for now.

I think the kid (aka account URL) is the best thing to key off for storing account info locally.

Thanks for making this update!

**Comment by FlorianUekermann** [comment]
Closing, because the API change I was keeping this open for will likely have to wait until December. The original issue is solved anyway, just not as nicely as it could be.
