### ISSUE TITLE
Bump to rustls 0.23

### ISSUE THREAD

**Issue by blind-oracle** [FlorianUekermann/rustls-acme#65]
Hello!

Simple bumping `futures-rustls` doesn't work since your custom `async-web-client` is still also on rustls-0.22 and client-config cannot be passed to it.

1) Bump `async-web-client` also to newer version
2) Switch to `reqwest` as an HTTP client instead to have one less crate to worry about?

I think (2) is nicer, I can do a PR if needed. Thanks.

**Comment by FlorianUekermann** [comment]
> 2\. Switch to `reqwest` as an HTTP client instead to have one less crate to worry about?

No, that's horrible ;-). This crate is fully runtime independent, I'm not aware of any other async http client libraries that are. That's why I did async-web-client in the first place. I'll push a new release for both in a few minutes.

**Comment by blind-oracle** [comment]
Thank you a lot 👍

**Comment by FlorianUekermann** [comment]
released 0.10.0
