### ISSUE TITLE
will cached certs be renewed automatically?

### ISSUE THREAD

**Issue by lichifeng** [FlorianUekermann/rustls-acme#68]
Does this rustls-acme periodically check the validity of cached certificates?    
Is it necessary to manually update the certificates?   

 I didn’t see any relevant explanation in the documentation. Thank you.

**Comment by FlorianUekermann** [comment]
It's not necessary to manually update certificates.

At startup a cached certificate is used to serve traffic immediately if the set of domains matches.

Certificate renewal is done automatically after 2/3 of the validity period has passed, so no periodic checks are necessary. If rustls-acme isn't running at that time (e.g. your server is offline), renewal is done immediately when it starts running again and the updated certificate should be available very quickly.

Does that answer your question? If not, an example scenario may help me understand.

**Comment by lichifeng** [comment]
> It's not necessary to manually update certificates.
> 
> At startup a cached certificate is used to serve traffic immediately if the set of domains matches.
> 
> Certificate renewal is done automatically after 2/3 of the validity period has passed, so no periodic checks are necessary. If rustls-acme isn't running at that time (e.g. your server is offline), renewal is done immediately when it starts running again and the updated certificate should be available very quickly.
> 
> Does that answer your question? If not, an example scenario may help me understand.

precisely!

thanks a lot.
